### ISSUE TITLE
[Idea] Dependency chain

### ISSUE THREAD

**Issue by OneCricketeer** [risdenk/apache-zeppelin-docker#1]
For example, the jdbc image would be re-written using a `FROM risdenk/zeppelin:netinstall`, then you just install the interpreters and their dependencies as new layers.  

For inspiration: see [Jupyter Docker Stacks](https://github.com/jupyter/docker-stacks)

**Comment by risdenk** [comment]
Theoretically yes it could. The issue is that all of the images are built in one repo on docker hub. So it's not easy to have one depend on the other. If it were a separate repo or manually updated could definitely do this.
